[phases.setup]
nixPkgs = ["flutter", "bash", "coreutils", "git", "python3"]

[phases.install]
cmds = [
    "flutter config --enable-web",
    "flutter pub get"
]

[phases.build]
cmds = [
    "flutter build web --base-href=/"
]

[start]
cmd = "python3 -m http.server 8080 --directory build/web"
